### ISSUE TITLE
[Question] Adding attributes to spans

### ISSUE THREAD

**Issue by brett-anderson** [corentinmusard/otel-cicd-action#16]
Hello! We are currently using https://github.com/honeycombio/gha-buildevents to trace our Github Actions, but are finding a few shortcomings:
- It is highly coupled to our workflows, making things hard to refactor
- Requires manual collection of attributes
- Does not have visibility on steps within jobs

Due to these issues we are exploring alternatives, and found this library. 

Sometimes we need to set custom attributes on the root span, depending on some conditions. Is there any suggestions on how to do this with this action? One example would be adding the labels from a pull request.

Thank you for maintaining! As an aside I found a small typo while reading through the examples, here is a [PR ](https://github.com/corentinmusard/otel-cicd-action/pull/15) to fix.

**Comment by brett-anderson** [comment]
@corentinmusard I've written a PR [here](https://github.com/corentinmusard/otel-cicd-action/pull/18) to introduce PR labels to traces, let me know if this is close to an approach you would consider implementing.

**Comment by corentinmusard** [comment]
Thanks a lot for the PR.
Really appreciate the tests, I'm aware that the test setup is far from ideal.

The only comment I have is to keep the labels as an array instead of a comma separated string (I pushed that to the PR).

**Comment by brett-anderson** [comment]
> Thanks a lot for the PR. Really appreciate the tests, I'm aware that the test setup is far from ideal.
> 
> The only comment I have is to keep the labels as an array instead of a comma separated string (I pushed that to the PR).

Works for me, thank you!
